apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "localstack.name" . }}
    helm.sh/chart: {{ include "localstack.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if contains "NodePort" .Values.service.type }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      {{- end }}

       - name: 
      enabled: false
      endpoint: ""
      internalPort: 4566
      externalPort: 4566
      nodePort:  31567
  {{- range $index, $val := .Values.localstack.services }}
  {{- if $val.enabled }}
    - name: {{ .Values.localstack.serviceName }}
      protocol: TCP
      port: {{ .Values.localstack.edgePort }}
      targetPort: {{ .Values.localstack.edgePort }}
      {{- if contains "NodePort" .Values.service.type }}
      {{- if .Values.localstack.nodePort }}
      nodePort: {{.Values.localstack.nodePort }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "localstack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
